const mongoose = require('mongoose');

const RegistrationModel = mongoose.Schema(
  {
    user: { name: String, email: String },
    address: { type: String },
    age: { type: String },

    studentName: { type: String },
    attDays: { type: String },
    attTime: { type: String },
    interestedSubject: [],
    subject: { type: String },
    description: { type: String },
    parentName: { type: String },
    phoneNumber: { type: String },
    regType: { type: String },
    teacherInfo: {},

    levels: {
      level1: String,
      level2: String,
      level3: String,
      level4: String,
      level5: String,
      level6: String,
      level7: String,
      level8: String,
      level9: String,
      level10: String,
    },

    MBPS: String,
    aboutDes: String,
    accountName: String,
    accountNumber: String,
    againstCountryActivities: String,
    aloneClass: String,
    bankName: String,
    bcn: String,
    bestQualAsTeacher: String,
    biggesPbmMuslim: String,
    biggesPbmMuslimSalution: String,
    birthC: String,
    branchCode: String,
    branchName: String,
    cCountry: String,
    cDetailsAddress: String,
    cDistrict: String,
    cDivision: String,
    cPostCode: String,
    cPostOffice: String,
    cThana: String,
    cantAskStudentPersonalInfo: String,
    classDevice: String,
    classTimechange: String,
    country: String,
    currentMadrashaName: String,
    detailsAddress: String,
    deviceModel: String,
    district: String,
    division: String,
    doNotStopClassBeforeTime: String,
    dob: String,
    eduQal1: String,
    eduQal2: String,
    eduQal3: String,
    eduQalAlmaMatter: String,
    eduQalResult: String,
    eduQalYear: String,
    eduQalYear1: String,
    eduQalAlmaMatter1: String,
    eduQalResult1: String,
    eduQalYear2: String,
    eduQalAlmaMatter2: String,
    eduQalResult2: String,
    educationLifeHighestMarksSub: String,
    email: String,
    expMadrasha: String,
    expPrevClass: [],
    expStudentBehave: String,
    expSubDay: String,
    expYoungerStudentBehave: String,
    fatherNid: String,
    fathersOrHbName: String,
    favoriouteMatterReason: String,
    firstName: String,
    followGuidesForClass: String,
    fvt3Alem: String,
    fvt3Books: String,
    fvtSubject: [],
    gender: String,
    generalLine: String,
    good5Quality: String,
    gurdianName: String,
    gurdianNidn: String,
    hollidayAppOneyBefore1Day: String,
    holydayApplyInClassTime: String,
    ifStudentMissClass: String,
    ifStudentMissConcentrate: String,
    informUsClassPbm: String,
    instituteName: String,
    institutionalResponsibility: String,
    interestedDpt: String,
    interestedSubject: String,
    interestedToJoinWithUsDay: String,
    isLaptopOrDextop: String,
    isMarried: String,
    isResFullAppointment: String,
    isWifiUser: String,
    lastName: String,
    mainSkillTopic: String,
    maxTwoDaysHoliday: String,
    mfsNumber: String,
    minFiveMonthTeaching: String,
    mustAtSunshinePlace: String,
    mustGiveStudentFeedback: String,
    nationality: String,
    nid: String,
    nidn: String,
    noCommunicationWithoutWeb: String,
    noContactInfoCanBeGiven: String,
    noWayClassMiss: String,
    noWorkDuringClass: String,
    obeyAllRules: String,
    obeyPolicyUs: String,
    parcel: String,
    paymentBasis: String,
    paymentCantbeShared: String,
    paymentMethod: String,
    paymentPerMonthDate: String,
    phoneNumber: String,
    politicalDiscussion: String,
    politicalLike: String,
    postCode: String,
    postOffice: String,
    prevExpMadrasha: String,
    prevExpSubDay: String,
    profile: String,
    puntualJoiningMeeting: String,
    puntualityComment: String,
    reasonForSelectiongSub: String,
    responseHurryClMsg: String,
    result: String,
    rightsChangingClassSchedule: String,
    routingNumber: String,
    setpForinterestingAnyMattersStudents: String,
    shouldHaveQual: String,
    studentDownInformUs: String,
    studentLifeCharacter: String,
    studentLifeCompetetion: String,
    studiedSubject: [],
    study: String,
    studyYear: String,

    thana: String,
    time1: String,
    time2: String,
    time3: String,
    time4: String,
    timeJoin: String,
    toBeFreeForOnlineClass: String,
    whatUrFamilySayAbtU: String,
    whatsYourIdeaToBringUsbetter: String,
    whyDoUWnatToTakeOnlineCls: String,
    whyIWnatToJoin: String,
    whyPeopleNotShowInterestForDin: String,
    whyPeopleNotShowInterestForDinSalution: String,
  },

  { timestamps: true }
);

const Registration = mongoose.model('Registration', RegistrationModel);

module.exports = Registration;
